# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import auxiliary_pb2 as auxiliary__pb2


class AuxiliaryServiceStub:
    """Owner: M4 (Network & API Lead)
    Auxiliary gRPC Channel for Heartbeats, Health Checks, and CKKS Public Key Distribution

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/fedmed.network.AuxiliaryService/HealthCheck',
                request_serializer=auxiliary__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=auxiliary__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.DistributeEvaluationKey = channel.unary_unary(
                '/fedmed.network.AuxiliaryService/DistributeEvaluationKey',
                request_serializer=auxiliary__pb2.KeyDistributionRequest.SerializeToString,
                response_deserializer=auxiliary__pb2.KeyDistributionResponse.FromString,
                _registered_method=True)
        self.SendHeartbeat = channel.unary_unary(
                '/fedmed.network.AuxiliaryService/SendHeartbeat',
                request_serializer=auxiliary__pb2.HeartbeatPing.SerializeToString,
                response_deserializer=auxiliary__pb2.HeartbeatPong.FromString,
                _registered_method=True)


class AuxiliaryServiceServicer:
    """Owner: M4 (Network & API Lead)
    Auxiliary gRPC Channel for Heartbeats, Health Checks, and CKKS Public Key Distribution

    """

    def HealthCheck(self, request, context):
        """Check connectivity and operational status of a hospital silo
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DistributeEvaluationKey(self, request, context):
        """Distribute TenSEAL CKKS evaluation keys (Galois + relin keys) to the central server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendHeartbeat(self, request, context):
        """Periodic heartbeat sent by hospital clients to maintain session in FL consortium
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuxiliaryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=auxiliary__pb2.HealthCheckRequest.FromString,
                    response_serializer=auxiliary__pb2.HealthCheckResponse.SerializeToString,
            ),
            'DistributeEvaluationKey': grpc.unary_unary_rpc_method_handler(
                    servicer.DistributeEvaluationKey,
                    request_deserializer=auxiliary__pb2.KeyDistributionRequest.FromString,
                    response_serializer=auxiliary__pb2.KeyDistributionResponse.SerializeToString,
            ),
            'SendHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHeartbeat,
                    request_deserializer=auxiliary__pb2.HeartbeatPing.FromString,
                    response_serializer=auxiliary__pb2.HeartbeatPong.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fedmed.network.AuxiliaryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fedmed.network.AuxiliaryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuxiliaryService:
    """Owner: M4 (Network & API Lead)
    Auxiliary gRPC Channel for Heartbeats, Health Checks, and CKKS Public Key Distribution

    """

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fedmed.network.AuxiliaryService/HealthCheck',
            auxiliary__pb2.HealthCheckRequest.SerializeToString,
            auxiliary__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DistributeEvaluationKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fedmed.network.AuxiliaryService/DistributeEvaluationKey',
            auxiliary__pb2.KeyDistributionRequest.SerializeToString,
            auxiliary__pb2.KeyDistributionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fedmed.network.AuxiliaryService/SendHeartbeat',
            auxiliary__pb2.HeartbeatPing.SerializeToString,
            auxiliary__pb2.HeartbeatPong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
