# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auxiliary.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

try:
  from google.protobuf import runtime_version as _runtime_version
except ImportError:  # protobuf<5
  _runtime_version = None
if _runtime_version is not None:
  _runtime_version.ValidateProtobufRuntimeVersion(
      _runtime_version.Domain.PUBLIC,
      7,
      35,
      1,
      '',
      'auxiliary.proto'
  )
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61uxiliary.proto\x12\x0e\x66\x65\x64med.network\"K\n\x12HealthCheckRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\x12\x11\n\tnode_name\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"\xdc\x01\n\x13HealthCheckResponse\x12:\n\x06status\x18\x01 \x01(\x0e\x32*.fedmed.network.HealthCheckResponse.Status\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x13\n\x0bserver_time\x18\x03 \x01(\x03\x12\x0f\n\x07message\x18\x04 \x01(\t\"R\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07HEALTHY\x10\x01\x12\x11\n\rBUSY_TRAINING\x10\x02\x12\x0c\n\x08\x44\x45GRADED\x10\x03\x12\r\n\tUNHEALTHY\x10\x04\"Y\n\x16KeyDistributionRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\x12\x10\n\x08key_type\x18\x02 \x01(\t\x12\x1c\n\x14public_context_bytes\x18\x03 \x01(\x0c\"U\n\x17KeyDistributionResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\x12\x13\n\x0b\x66ingerprint\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"|\n\rHeartbeatPing\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\x12\x15\n\rcurrent_round\x18\x02 \x01(\x05\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x17\n\x0fmemory_usage_mb\x18\x04 \x01(\x01\x12\x17\n\x0fgpu_utilization\x18\x05 \x01(\x01\"m\n\rHeartbeatPong\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\x12\x13\n\x0bserver_time\x18\x02 \x01(\x03\x12\x1c\n\x14\x63urrent_server_round\x18\x03 \x01(\x05\x12\x13\n\x0bnext_action\x18\x04 \x01(\t2\xa5\x02\n\x10\x41uxiliaryService\x12V\n\x0bHealthCheck\x12\".fedmed.network.HealthCheckRequest\x1a#.fedmed.network.HealthCheckResponse\x12j\n\x17\x44istributeEvaluationKey\x12&.fedmed.network.KeyDistributionRequest\x1a\'.fedmed.network.KeyDistributionResponse\x12M\n\rSendHeartbeat\x12\x1d.fedmed.network.HeartbeatPing\x1a\x1d.fedmed.network.HeartbeatPongb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auxiliary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHCHECKREQUEST']._serialized_start=35
  _globals['_HEALTHCHECKREQUEST']._serialized_end=110
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=113
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=333
  _globals['_HEALTHCHECKRESPONSE_STATUS']._serialized_start=251
  _globals['_HEALTHCHECKRESPONSE_STATUS']._serialized_end=333
  _globals['_KEYDISTRIBUTIONREQUEST']._serialized_start=335
  _globals['_KEYDISTRIBUTIONREQUEST']._serialized_end=424
  _globals['_KEYDISTRIBUTIONRESPONSE']._serialized_start=426
  _globals['_KEYDISTRIBUTIONRESPONSE']._serialized_end=511
  _globals['_HEARTBEATPING']._serialized_start=513
  _globals['_HEARTBEATPING']._serialized_end=637
  _globals['_HEARTBEATPONG']._serialized_start=639
  _globals['_HEARTBEATPONG']._serialized_end=748
  _globals['_AUXILIARYSERVICE']._serialized_start=751
  _globals['_AUXILIARYSERVICE']._serialized_end=1044
# @@protoc_insertion_point(module_scope)
